#ifndef MIDI_H
#define MIDI_H

// Midi Continuous Controller Codes
// http://www.borg.com/~jglatt/tech/midispec/ctllist.htm
enum {
	MIDICC_start = 0,
	MIDICC_BankSelect_Coarse = MIDICC_start,
	MIDICC_ModulationWheel_Coarse = 1,
	MIDICC_Breathcontroller_Coarse = 2,
	MIDICC_FootPedal_Coarse = 4,
	MIDICC_PortamentoTime_Coarse = 5,
	MIDICC_DataEntry_Coarse = 6,
	MIDICC_Volume_Coarse = 7,
	MIDICC_Balance_Coarse = 8,
	MIDICC_Panposition_Coarse = 10,
	MIDICC_Expression_Coarse = 11,
	MIDICC_EffectControl1_Coarse = 12,
	MIDICC_EffectControl2_Coarse = 13,
	MIDICC_GeneralPurposeSlider1 = 16,
	MIDICC_GeneralPurposeSlider2 = 17,
	MIDICC_GeneralPurposeSlider3 = 18,
	MIDICC_GeneralPurposeSlider4 = 19,
	MIDICC_BankSelect_Fine = 32,
	MIDICC_ModulationWheel_Fine = 33,
	MIDICC_Breathcontroller_Fine = 34,
	MIDICC_FootPedal_Fine = 36,
	MIDICC_PortamentoTime_Fine = 37,
	MIDICC_DataEntry_Fine = 38,
	MIDICC_Volume_Fine = 39,
	MIDICC_Balance_Fine = 40,
	MIDICC_Panposition_Fine = 42,
	MIDICC_Expression_Fine = 43,
	MIDICC_EffectControl1_Fine = 44,
	MIDICC_EffectControl2_Fine = 45,
	MIDICC_HoldPedal_OnOff = 64,
	MIDICC_Portamento_OnOff = 65,
	MIDICC_SustenutoPedal_OnOff = 66,
	MIDICC_SoftPedal_OnOff = 67,
	MIDICC_LegatoPedal_OnOff = 68,
	MIDICC_Hold2Pedal_OnOff = 69,
	MIDICC_SoundVariation = 70,
	MIDICC_SoundTimbre = 71,
	MIDICC_SoundReleaseTime = 72,
	MIDICC_SoundAttackTime = 73,
	MIDICC_SoundBrightness = 74,
	MIDICC_SoundControl6 = 75,
	MIDICC_SoundControl7 = 76,
	MIDICC_SoundControl8 = 77,
	MIDICC_SoundControl9 = 78,
	MIDICC_SoundControl10 = 79,
	MIDICC_GeneralPurposeButton1_OnOff = 80,
	MIDICC_GeneralPurposeButton2_OnOff = 81,
	MIDICC_GeneralPurposeButton3_OnOff = 82,
	MIDICC_GeneralPurposeButton4_OnOff = 83,
	MIDICC_EffectsLevel = 91,
	MIDICC_TremuloLevel = 92,
	MIDICC_ChorusLevel = 93,
	MIDICC_CelesteLevel = 94,
	MIDICC_PhaserLevel = 95,
	MIDICC_DataButtonincrement = 96,
	MIDICC_DataButtondecrement = 97,
	MIDICC_NonRegisteredParameter_Fine = 98,
	MIDICC_NonRegisteredParameter_Coarse = 99,
	MIDICC_RegisteredParameter_Fine = 100,
	MIDICC_RegisteredParameter_Coarse = 101,
	MIDICC_AllSoundOff = 120,
	MIDICC_AllControllersOff = 121,
	MIDICC_LocalKeyboard_OnOff = 122,
	MIDICC_AllNotesOff = 123,
	MIDICC_OmniModeOff = 124,
	MIDICC_OmniModeOn = 125,
	MIDICC_MonoOperation = 126,
	MIDICC_PolyOperation = 127,
	MIDICC_end = MIDICC_PolyOperation,
};

enum {
	MIDI_PitchBend_Command = 0xE0,
	MIDI_PitchBend_Min     = 0x00,
	MIDI_PitchBend_Centre  = 0x2000,
	MIDI_PitchBend_Max     = 0x3FFF
};


static CString MidiCCNames[MIDICC_end+1] ={
"BankSelect [Coarse]",
"ModulationWheel [Coarse]",
"Breathcontroller [Coarse]",
"FootPedal [Coarse]",
"PortamentoTime [Coarse]",
"DataEntry [Coarse]",
"Volume [Coarse]",
"Balance [Coarse]",
"Panposition [Coarse]",
"Expression [Coarse]",
"EffectControl1 [Coarse]",
"EffectControl2 [Coarse]",
"GeneralPurposeSlider1",
"GeneralPurposeSlider2",
"GeneralPurposeSlider3",
"GeneralPurposeSlider4",
"BankSelect [Fine]",
"ModulationWheel [Fine]",
"Breathcontroller [Fine]",
"FootPedal [Fine]",
"PortamentoTime [Fine]",
"DataEntry [Fine]",
"Volume [Fine]",
"Balance [Fine]",
"Panposition [Fine]",
"Expression [Fine]",
"EffectControl1 [Fine]",
"EffectControl2 [Fine]",
"HoldPedal [OnOff]",
"Portamento [OnOff]",
"SustenutoPedal [OnOff]",
"SoftPedal [OnOff]",
"LegatoPedal [OnOff]",
"Hold2Pedal [OnOff]",
"SoundVariation",
"SoundTimbre",
"SoundReleaseTime",
"SoundAttackTime",
"SoundBrightness",
"SoundControl6",
"SoundControl7",
"SoundControl8",
"SoundControl9",
"SoundControl10",
"GeneralPurposeButton1 [OnOff]",
"GeneralPurposeButton2 [OnOff]",
"GeneralPurposeButton3 [OnOff]",
"GeneralPurposeButton4 [OnOff]",
"EffectsLevel",
"TremuloLevel",
"ChorusLevel",
"CelesteLevel",
"PhaserLevel",
"DataButtonIncrement",
"DataButtonDecrement",
"NonRegisteredParameter [Fine]",
"NonRegisteredParameter [Coarse]",
"RegisteredParameter [Fine]",
"RegisteredParameter [Coarse]",
"AllSoundOff",
"AllControllersOff",
"LocalKeyboard [OnOff]",
"AllNotesOff",
"OmniModeOff",
"OmniModeOn",
"MonoOperation",
"PolyOperation",
};


#endif
