// generated 1999/12/23 5:10:22 CST by temporal@temporal.
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/temporal/stf/src/modplug/glade/modinfo/modinfo.glade
// for gtk 1.2.5 and gtkmm 1.0.2
//
// Please modify the corresponding derived classes in src/CModinfoWindow.cc

#include "modinfowin.h"

CModinfoWindow_Glade::CModinfoWindow_Glade(
) : Gtk_Window(GTK_WINDOW_TOPLEVEL), label4("Filename:\n"
		"Title:\n"
		"Type:\n"
		"Length:\n"
		"Speed:\n"
		"Tempo:\n"
		"Samples:\n"
		"Instruments:\n"
		"Patterns:\n"
		"Channels:"), generalinfo("---\n"
		"---\n"
		"---\n"
		"---\n"
		"---\n"
		"---\n"
		"---\n"
		"---\n"
		"---\n"
		"---"), label1("General"), samplebox(""), label2("Samples"), instrumentbox(""), label3("Instruments"), closebtn("Close")
{   label4.set_name("label4");
   label4.set_alignment(0.5, 0.5);
   label4.set_padding(0, 0);
   generalinfo.set_name("generalinfo");
   generalinfo.set_alignment(0.5, 0.5);
   generalinfo.set_padding(0, 0);
   hbox2.set_name("hbox2");
   hbox2.pack_start(label4, false, false, 4);
   hbox2.pack_start(generalinfo, false, false, 4);
   label1.set_name("label1");
   label1.set_alignment(0.5, 0.5);
   label1.set_padding(0, 0);
   samplebox.set_name("samplebox");
   samplebox.set_alignment(7.45058e-09, 7.45058e-09);
   samplebox.set_padding(0, 0);
   viewport1.set_name("viewport1");
   viewport1.add(&samplebox);
   scrolledwindow1.set_name("scrolledwindow1");
   scrolledwindow1.set_border_width(4);
   scrolledwindow1.set_policy(GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
   scrolledwindow1.add(&viewport1);
   label2.set_name("label2");
   label2.set_alignment(0.5, 0.5);
   label2.set_padding(0, 0);
   instrumentbox.set_name("instrumentbox");
   instrumentbox.set_alignment(1.49012e-08, 7.45058e-09);
   instrumentbox.set_padding(0, 0);
   viewport2.set_name("viewport2");
   viewport2.add(&instrumentbox);
   scrolledwindow2.set_name("scrolledwindow2");
   scrolledwindow2.set_border_width(4);
   scrolledwindow2.set_policy(GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
   scrolledwindow2.add(&viewport2);
   label3.set_name("label3");
   label3.set_alignment(0.5, 0.5);
   label3.set_padding(0, 0);
   notebook1.set_name("notebook1");
   notebook1.set_show_tabs(true);
   notebook1.set_tab_border(3);
   notebook1.append_page(hbox2, label1);
   notebook1.append_page(scrolledwindow1, label2);
   notebook1.append_page(scrolledwindow2, label3);
   closebtn.set_usize(65, 27);
   closebtn.set_name("closeBtn");
   connect_to_method(closebtn.clicked, (CModinfoWindow*)this, &CModinfoWindow::on_closeBtn_clicked);
   hbox1.set_name("hbox1");
   hbox1.pack_start(closebtn, false, false, 5);
   vbox1.set_name("vbox1");
   vbox1.pack_start(notebook1, true, true, 8);
   vbox1.pack_start(hbox1, false, false, 0);
   set_usize(290, 240);
   set_name("CModinfoWindow");
   set_title("MOD Info");
   set_policy(false, false, false);
   add(&vbox1);
   label4.show();
   generalinfo.show();
   hbox2.show();
   label1.show();
   samplebox.show();
   viewport1.show();
   scrolledwindow1.show();
   label2.show();
   instrumentbox.show();
   viewport2.show();
   scrolledwindow2.show();
   label3.show();
   notebook1.show();
   closebtn.show();
   hbox1.show();
   vbox1.show();
   show();
}

CModinfoWindow_Glade::~CModinfoWindow_Glade()
{   
}
