// generated 1999/12/23 5:10:22 CST by temporal@temporal.
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/temporal/stf/src/modplug/glade/modinfo/modinfo.glade
// for gtk 1.2.5 and gtkmm 1.0.2
//
// Please modify the corresponding derived classes in src/CModinfoWindow.hh andsrc/CModinfoWindow.cc

#ifndef _CMODINFOWINDOW_GLADE_HH
#  define _CMODINFOWINDOW_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>
#include <gtk--/box.h>
#include <gtk--/viewport.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/notebook.h>
#include <gtk--/button.h>

class CModinfoWindow_Glade : public Gtk_Window
{
protected:
        Gtk_Label label4;
        Gtk_Label generalinfo;
        Gtk_HBox hbox2;
        Gtk_Label label1;
        Gtk_Label samplebox;
        Gtk_Viewport viewport1;
        Gtk_ScrolledWindow scrolledwindow1;
        Gtk_Label label2;
        Gtk_Label instrumentbox;
        Gtk_Viewport viewport2;
        Gtk_ScrolledWindow scrolledwindow2;
        Gtk_Label label3;
        Gtk_Notebook notebook1;
        Gtk_Button closebtn;
        Gtk_HBox hbox1;
        Gtk_VBox vbox1;

        CModinfoWindow_Glade();
        
        ~CModinfoWindow_Glade();
};
#endif
