// generated 1999/12/18 23:45:52 CST by temporal@temporal.
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/temporal/stf/src/modplug/glade/configure/modplug.glade
// for gtk 1.2.5 and gtkmm 1.0.2
//
// Please modify the corresponding derived classes in src/configwin.hh andsrc/configwin.cc

#ifndef _CONFIGWIN_GLADE_HH
#  define _CONFIGWIN_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/radiobutton.h>
#include <gtk--/box.h>
#include <gtk--/frame.h>
#include <gtk--/label.h>
#include <gtk--/checkbutton.h>
#include <gtk--/scale.h>
#include <gtk--/table.h>
#include <gtk--/notebook.h>
#include <gtk--/button.h>
#include <gtk--/fixed.h>

class CConfigureWindow_Glade : public Gtk_Window
{
protected:
        Gtk_RadioButton *bit16;
        Gtk_RadioButton *bit8;
        Gtk_VBox vbox13;
        Gtk_Frame frame9;
        Gtk_RadioButton *stereo;
        Gtk_RadioButton *mono;
        Gtk_VBox vbox14;
        Gtk_Frame frame10;
        Gtk_HBox hbox8;
        Gtk_RadioButton *samp44;
        Gtk_RadioButton *samp22;
        Gtk_RadioButton *samp11;
        Gtk_VBox vbox15;
        Gtk_Frame frame11;
        Gtk_VBox vbox12;
        Gtk_Label label10;
        Gtk_CheckButton fxoversamp;
        Gtk_CheckButton fxnr;
        Gtk_VBox vbox17;
        Gtk_CheckButton fxvolramp;
        Gtk_CheckButton fxfastinfo;
        Gtk_VBox vbox18;
        Gtk_HBox hbox9;
        Gtk_Frame frame12;
        Gtk_CheckButton fxreverbon;
        Gtk_HScale *fxreverbdepth;
        Gtk_Adjustment *fxreverbdepth_adj;
        Gtk_HScale *fxreverbdelay;
        Gtk_Adjustment *fxreverbdelay_adj;
        Gtk_Label label11;
        Gtk_Label label12;
        Gtk_Table table6;
        Gtk_VBox vbox19;
        Gtk_HBox hbox10;
        Gtk_Frame frame13;
        Gtk_CheckButton fxbasson;
        Gtk_HScale *fxbassamount;
        Gtk_Adjustment *fxbassamount_adj;
        Gtk_HScale *fxbassrange;
        Gtk_Adjustment *fxbassrange_adj;
        Gtk_Label label13;
        Gtk_Label label14;
        Gtk_Table table7;
        Gtk_VBox vbox20;
        Gtk_HBox hbox11;
        Gtk_Frame frame14;
        Gtk_CheckButton fxsurroundon;
        Gtk_HScale *fxsurrounddepth;
        Gtk_Adjustment *fxsurrounddepth_adj;
        Gtk_HScale *fxsurrounddelay;
        Gtk_Adjustment *fxsurrounddelay_adj;
        Gtk_Label label15;
        Gtk_Label label16;
        Gtk_Table table8;
        Gtk_VBox vbox21;
        Gtk_HBox hbox12;
        Gtk_Frame frame15;
        Gtk_CheckButton fxfadeon;
        Gtk_Label label17;
        Gtk_HScale *fxfadetime;
        Gtk_Adjustment *fxfadetime_adj;
        Gtk_HBox hbox14;
        Gtk_VBox vbox22;
        Gtk_HBox hbox13;
        Gtk_Frame frame16;
        Gtk_VBox vbox16;
        Gtk_Label label18;
        Gtk_Notebook notebook2;
        Gtk_Button okbtn;
        Gtk_Button applybtn;
        Gtk_Button cancelbtn;
        Gtk_Fixed fixed1;
        Gtk_VBox vbox23;

        CConfigureWindow_Glade();
        ~CConfigureWindow_Glade();

private:
	//constructor was too long.  had to be split up to get decent compile times.
	void init1();
	void init2();
	void init3();
	void init4();
	void init5();
};
#endif
