// generated 1999/12/18 23:45:52 CST by temporal@temporal.
// using glademm V0.5.5
//
// some glademm convenience functions
//
// DO NOT EDIT THIS FILE !

#ifndef GLADEMM_SUPPORT_HH
#define GLADEMM_SUPPORT_HH
#include <string>
#include <map>
#include <glib.h>

GSList * glademm_get_RadioGroup(const string &name);
void glademm_set_RadioGroup(const string &name, GSList *val);
#endif /* GLADEMM_SUPPORT_HH */
