// generated 1999/12/18 23:45:52 CST by temporal@temporal.
// using glademm V0.5.5
//
// some glademm convenience functions
//
// DO NOT EDIT THIS FILE !

#include "glademm_support.h"

static map<const string,GSList *> glademm_radiogroups;

GSList * glademm_get_RadioGroup(const string &name)
{   
   
   map<const string,GSList *>::iterator i=glademm_radiogroups.find(name);
   if (i==glademm_radiogroups.end()) return 0;
   return (*i).second;
}

void glademm_set_RadioGroup(const string &name, GSList *val)
{   glademm_radiogroups[name]=val;
}
