
#pragma once

#define OPENMPT_VERSION_URL ""
#define OPENMPT_VERSION_REVISION 0

#define OPENMPT_VERSION_DIRTY false
#define OPENMPT_VERSION_MIXEDREVISIONS false

#define OPENMPT_VERSION_DATE __DATE__ " " __TIME__
