// generated 1999/12/22 0:02:4 CST by temporal@temporal.
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/temporal/stf/src/modplug/glade/about/about.glade
// for gtk 1.2.5 and gtkmm 1.0.2
//
// Please modify the corresponding derived classes in src/CAboutWindow.hh andsrc/CAboutWindow.cc

#ifndef _CABOUTWINDOW_GLADE_HH
#  define _CABOUTWINDOW_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>
#include <gtk--/separator.h>
#include <gtk--/button.h>
#include <gtk--/box.h>

class CAboutWindow_Glade : public Gtk_Window
{   
        
        Gtk_Label label1;
        Gtk_HSeparator hseparator1;
        Gtk_Button okbtn;
        Gtk_HBox hbox1;
        Gtk_VBox vbox1;
protected:
        
        CAboutWindow_Glade();
        
        ~CAboutWindow_Glade();
};
#endif
