// generated 1999/12/22 0:02:4 CST by temporal@temporal.
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/temporal/stf/src/modplug/glade/about/about.glade
// for gtk 1.2.5 and gtkmm 1.0.2
//
// Please modify the corresponding derived classes in src/CAboutWindow.cc

#include "aboutwin.h"

CAboutWindow_Glade::CAboutWindow_Glade(
) : Gtk_Window(GTK_WINDOW_TOPLEVEL), label1("Modplug Input Plugin for XMMS\n"
		"Modplug sound engine written by Olivier Lapicque.\n"
		"XMMS interface for Modplug by Kenton Varda.\n"
		"(c)1999 Olivier Lapicque and Kenton Varda"), okbtn("OK")
{   label1.set_name("label1");
   label1.set_alignment(0.5, 0.5);
   label1.set_padding(0, 0);
   hseparator1.set_usize(-1, 18);
   hseparator1.set_name("hseparator1");
   okbtn.set_usize(121, 29);
   okbtn.set_name("okBtn");
   connect_to_method(okbtn.clicked, (CAboutWindow*)this, &CAboutWindow::on_okBtn_clicked);
   hbox1.set_name("hbox1");
   hbox1.pack_start(okbtn, false, false, 0);
   vbox1.set_name("vbox1");
   vbox1.pack_start(label1, false, false, 0);
   vbox1.pack_start(hseparator1);
   vbox1.pack_start(hbox1);
   set_name("CAboutWindow");
   set_title("About Modplug");
   set_policy(false, false, false);
   add(&vbox1);
   label1.show();
   hseparator1.show();
   okbtn.show();
   hbox1.show();
   vbox1.show();
   show();
}

CAboutWindow_Glade::~CAboutWindow_Glade()
{   
}
