name: FreeBSD 13.5 Makefile

on:
  push:
    branches: [ OpenMPT-1.29 ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: '13.5'
        shell: bash
        sync_files: runner-to-vm
        shutdown_vm: false
        run: true
    - name: Install dependencies
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: '13.5'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sudo pkg upgrade -y
          sudo pkg install -y subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2
    - name: Build
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: '13.5'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1
    - name: Test
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: '13.5'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
    - name: Shutdown VM
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: '13.5'
        shell: bash
        sync_files: false
        shutdown_vm: true
        run: true
