name: macOS 12 Makefile

on:
  push:
    branches: [ OpenMPT-1.30 ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - name: update Homebrew
      run: brew update
    - name: fixup GitHub Homebrew swiftlint breakage
      run: brew pin swiftlint
    - name: fixup GitHub Homebrew xcbeautify breakage
      run: brew pin xcbeautify
    - name: fixup GitHub Homebrew go breakage
      run: brew unlink go@1.21 && brew unlink go && brew link --overwrite go
    - name: fixup GitHub Homebrew node breakage
      run: brew unlink node@18 && brew unlink node && brew link --overwrite node
    - name: fixup GitHub Homebrew python breakage
      run: brew unlink python@3.11 && brew unlink python@3.12 && brew link --overwrite python@3.11 && brew link --overwrite python@3.12
    - name: install dependencies
      run: brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile sdl2
    - name: setup parallel make
      run: echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
    - name: make
      run: make STRICT=1 FORCE_DEPS=1
    - name: make check
      run: make STRICT=1 FORCE_DEPS=1 check
