name: MidnightBSD Autotools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '4.0.4' }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-autotools
      cancel-in-progress: true

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@v1.2.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: midnightbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
    - name: Sync files to VM
      shell: cpa.sh {0} --sync-files runner-to-vm
      run: true
    - name: Install dependencies
      shell: cpa.sh {0} --sync-files none
      run: |
        sudo mport index
        sudo mport upgrade
        sudo mport install subversion p5-XML-TreePP git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2 || true
    - name: Build
      shell: cpa.sh {0} --sync-files none
      run: |
        export MAKEFLAGS="-j$(sysctl -n hw.ncpu)"; ./build/autotools/autoconfiscate.sh
