name: MSYS2 Makefile

on:
  push:
    branches: [ OpenMPT-1.32 ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - { sys: MINGW64, rep: mingw64, env: x86_64 }
          - { sys: MINGW32, rep: mingw32, env: i686 }
          - { sys: UCRT64,  rep: ucrt64,  env: ucrt-x86_64 }
    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.sys}}-${{matrix.rep}}-${{matrix.env}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: msys/base-devel msys/autoconf ${{matrix.rep}}/mingw-w64-${{matrix.env}}-toolchain msys/autoconf-archive msys/automake msys/ccache msys/doxygen msys/gawk msys/help2man msys/libtool msys/git msys/p7zip msys/perl-XML-LibXML msys/subversion msys/unzip msys/xz msys/zip ${{matrix.rep}}/mingw-w64-${{matrix.env}}-clang ${{matrix.rep}}/mingw-w64-${{matrix.env}}-flac ${{matrix.rep}}/mingw-w64-${{matrix.env}}-libltdl ${{matrix.rep}}/mingw-w64-${{matrix.env}}-libogg ${{matrix.rep}}/mingw-w64-${{matrix.env}}-libsndfile ${{matrix.rep}}/mingw-w64-${{matrix.env}}-libvorbis ${{matrix.rep}}/mingw-w64-${{matrix.env}}-mpg123 ${{matrix.rep}}/mingw-w64-${{matrix.env}}-portaudio ${{matrix.rep}}/mingw-w64-${{matrix.env}}-pulseaudio ${{matrix.rep}}/mingw-w64-${{matrix.env}}-SDL2 ${{matrix.rep}}/mingw-w64-${{matrix.env}}-zlib
      - name: setup parallel make
        run: echo MAKEFLAGS=-j${NUMBER_OF_PROCESSORS} >> $GITHUB_ENV
      - name: make
        run: make
      - name: make check
        run: make check
